### ISSUE TITLE
!cr command broken

### ISSUE THREAD

**Issue by CocoaMix86** [bra1n/judgebot#167] opened 2022-05-23 02:30 UTC
![image](https://user-images.githubusercontent.com/5726733/169732161-29311c9c-a925-439a-9b37-883afaa1cdc0.png)

I did notice that trying to go to the comprehensive rules site from WOTC gives this:
https://rules.wizards.com/rulebook.aspx?game=Magic&category=Game+Rules
![image](https://user-images.githubusercontent.com/5726733/169732257-f6854e18-c0b3-40dd-9d4f-ec2ef3f19cfb.png)

And the new site is over here now
https://blogs.magicjudges.org/rules/cr/

**Comment by multimeric** [comment] 2022-05-23 02:37
I believe the actual CR behaviour is fixed by my PR: #159. However as you say the URL has changed so I should probably redirect users to the new location with the hyperlink.

**Comment by lunakv** [comment] 2022-05-24 08:33
The actual problem might be much more pragmatic. Venser's Journal has been basically shut down, and `https://cr.vensersjournal.com` no longer redirects to the current rules file, but just returns a 404. As that's the URL that the bot uses to retrieve the file, it doesn't have anything to work with anymore.

**Comment by multimeric** [comment] 2022-05-24 08:44
How weird. I actually wrote a parser for the official CR (plaintest), which is here: https://github.com/multimeric/VensersJournal/tree/mtr-parser/scraper. When I get time I'll find a way to integrate it here.

**Comment by lunakv** [comment] 2022-05-24 08:54
I don't think the problem is even parsing per se, that the bot can do. It's just that because that link is down, the bot doesn't even get the rules file. As an aside, the link you provided seems to be a parser for the MTR, not the CR?

(I'm currently in talks with a few people about restoring at least the rules API of VJ in some fashion, btw.)

**Comment by multimeric** [comment] 2022-05-24 09:02
Right, I mixed them up. I think for the CR I added a plaintext parser in my PR: https://github.com/bra1n/judgebot/pull/159/files#diff-63fbf67a107117fba4b8a0ad4c02b79c6cc30c1333639ca5b1acb00d817347a7, which also doesn't depend on Venser's Journal

**Comment by lunakv** [comment] 2022-05-24 09:05
Sure. That's what the bot already does now. It doesn't depend on VJ for the actual parsing, just for the URL to get the plain text rules file.

**Comment by multimeric** [comment] 2022-05-24 09:09
Oh, well that should be easy to scrape directly from the Wizards site.

**Comment by lunakv** [comment] 2022-05-24 09:12
Yeah, that should be possible. Like I said, we're currently working on recreating the API, so hopefully we could just replace the dependency and the bot wouldn't have to do the scraping itself.

**Comment by multimeric** [comment] 2022-05-24 09:14
What happened to VJ? The GitHub also seems to have lost some commits from a PR I made to it. If you're willing to maintain VJ, could you find a way to wire my MTR parser into the API? The original intention was to have it there, so that others could use it, not just judgebot.

**Comment by multimeric** [comment] 2022-05-24 09:16
I ask because I would want to remove the VJ dependency if it's unlikely to be maintained in an ongoing fashion.

**Comment by lunakv** [comment] 2022-05-24 09:34
The details are unclear, but to sum it up - the owner of VJ had a falling out with the judge community, decided to shut the whole thing down, and nuked the original repo. The repo your fork is based on is itself a fork that's about 2 years out of date, but it was the best remnant of the original we had, though it appears yours is more up-to-date, which is great.

As far as further maintenance, discussions are ongoing (this all happened literally two days ago), but at least the API portion of VJ should be restored before the original goes down fully (i.e. before June 1), almost definitely on a different domain of course. Right now I'm focused on the API as that's what other projects depend on, but depending on how that goes, the full website should hopefully also be recreatable in the future. The new API should be dependable long-term, and as there are other projects that either parse the CR or use the parsed representations from VJ, I'd prefer the development be centralized there rather than each bot parsing it on its own. 

Once things are up and running, a MTR integration would be a great feature! I'll make sure to send a message here once we have anything more concrete (like I said, it's still an ongoing situation).

**Comment by lunakv** [comment] 2022-05-26 05:46
@multimeric A working version of the new API [is online](https://api.academyruins.com). You can check out the [source code](https://github.com/lunakv/academyruins-api), though it's a little hacked together at the moment and needs some cleaning up (but that's a problem for post-finals me :slightly_smiling_face: )

**Closed as completed** 2022-05-26 21:05 UTC
